### ISSUE TITLE
OOM issue not reported on jupyterlab

### ISSUE THREAD

**Issue by 3C111** [SwissDataScienceCenter/renku-notebooks#104]
On Renkulab: If an operation in a notebook runs out of memory, this is not reported by Jupyterlab. The kernel will restart, but cell will continue to appear to be pending. There is no error message in the notebook itself.

**Comment by rokroskar** [comment]
is this a renku problem or a jupyter problem? also, are you certain it was an OOM?

**Comment by 3C111** [comment]
I don't know, I am guessing it is rather a Jupyterlab problem. But since I have only used Jupyterlab in Renku-context, I cannot know for sure. 

As there are no logs it is not sure if it is an OOM issue, but it is the most likely culprit since the problem appears on operations that take a lot of memory. 

To clarify what I meant:  the kernel of the notebook dies and restarts (this is clear from the fact that all variables and imports are lost). Normally when using Jupyter notebooks it is clear when the kernel restarts. In this case, the cell continues to be marked as pending (i.e. the little star next to the cell) and there is no warning. So the operation just seems to take forever, when in reality the kernel has restarted and nothing is happening.

**Comment by rokroskar** [comment]
I think this is a Jupyterlab problem -- if there is some indication to believe otherwise, please reopen.
