### ISSUE TITLE
do not use local node disk space for user pods

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#106]
Two possibilities here: 

1. use PVs with retain policy `DELETE` so that the volumes are automatically removed when the pod is gone. 
2. have a large shared volume where we keep state of user sessions - this would require a service to do maintenance and cleanup of these directories. 

The first option above should be easy to implement. It involves the k8s admin creating a `temporary` (or equivalent name) `storageClass` and changing the volume spec in the spawners code. We should check if this `storageClass` exists before trying to use it and if not use `emptyDir` as we do now.

----

_(edited by @ableuler 2020-11-18)_
I would like to add two more options:

3. use PV's with retain policy `DELETE` similar to 1), but make the user environments `statefulSets` rather than "naked" pods. This would allow a pod to be recreated (for example in the case of a node failure) and prevent users from loosing data.

4. rather than having persistent state of individual user sessions, we could have persistent space for users, similar to a users home directory on shared HPC infrastructure. A repo would simply be cloned into this space when an environment is launched. However, to enable this we would have to mount the same volume to different user pods (same as for 2). This is similar to what was requested in https://github.com/SwissDataScienceCenter/renku-notebooks/issues/149.

**Comment by rokroskar** [comment]
We should more clearly outline the expected use-cases - for example, we might even have different "clases" of users (institutional vs. external) for which different resource limits should apply. For now we will enforce a 20GB limit for interactive sessions and work on setting up policies. Therefore this issue is pushed into the backlog.

**Comment by ableuler** [comment]
The two options outlined in the description have very different goals in mind: 

1. Nothing changes for the user, except that they don't loose their work when someone pulls the plug on the node that is running their session.
2. There is some degree of persistence between different user sessions.

I would propose to start with option 1). It seems much clearer in terms of user story and I think having done 1) will also help us to hash out 2) at some point in the future. 

Option 1) could be implemented by modelling the user sessions as statefulSets which have a persistent volume attached. What is very unclear to me is to what extent the existing JupyterHub based way of spawning and exposing user sessions would have to be adapted for this.

**Comment by ableuler** [comment]
Putting on pause for one sprint as other topics have higher priority.
