### ISSUE TITLE
Long term metric and session usage storage

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#1069]
This issue is needed to define two things:
1. Long term storage of metrics that @SwissDataScienceCenter/ordes is interested in to measure user activity and engagement
2. Provide means for tracking user activity and usage so that (if required) it can be used to determine costs

The idea is that this issue just outlines the approach and if possible provides a minimal implementation.

**Comment by olevski** [comment]
The main reason that we need this is because the retention of metrics in Prometheus is not permanent or long term.

Currently our prometheus instances (by default) retain the latest several weeks of data. Therefore long term trends in user activity (or any metric for that matter) cannot be tracked.

**Comment by olevski** [comment]
@gavin-k-lee can you comment ideally what information about each session you would like to see in a database or a log?

**Comment by gavin-k-lee** [comment]
@olevski could we start with these? https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2215837710/Quantitative+Community+and+Usage+Metrics#Desirable-metrics-for-user-sessions
