### ISSUE TITLE
S3 bucket mounting when wrong credentials

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-notebooks#1120]
When I try to mount S3 buckets to a session, and then enter the incorrect credentials, I just get kicked out to the 'No session running' page. Would it be possible to indicate this error somehow after we try to open the session, and then allow the user to 'Retry credentials', 'Start session without buckets' or 'Exit' or something like that?

In the case of multiple buckets, if at least one fails it will kick out everything.

Could we have a think about a design for this?

**Comment by olevski** [comment]
will be fixed by #849
