### ISSUE TITLE
requesting no gpus results in no limit on gpus

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#114]
we should set gpu limit to `0` instead of passing `None` if no gpu is requested. At the moment, a user that doesn't request a gpu gets access to all the gpus.

**Comment by olevski** [comment]
@rokroskar this is an old issue and this is definitely not the case today. We recently added [this section](https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/helm-chart/renku-notebooks/values.yaml#L187-L193) which applies these defaults when the user omits to select/define a value in the request and I also checked on limited that the "0" gpu selection is passed on to the notebook service.
