### ISSUE TITLE
Mount or link `/cloudstorage` folder in the user project directory

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#1165]
Users who use the s3 feature are sometimes confused about where they can access their data.

Therefore it would be nice to mount the s3 storage folder in the user's project directory.

Currently we use `/cloudstorage` to mount all the buckets in. And the users get the info about where to access the buckets when they specify the bucket credentials when they launch the sessions. But it is easy to miss this.

**Comment by Panaetius** [comment]
Test with renku cli (renku dataset add, renku run, renku workflow execute, etc.) using this symlinked folder.

Symlink manually and check that everything works.
