### ISSUE TITLE
Add a save function to the session sidecar

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#1175]
This can be used by the ui to save unsaved work in a user's session when a user tries to shut down a session that has unsaved work.

**Comment by andre-code** [comment]
Please also include the _Refresh_ function.
Ref: https://github.com/SwissDataScienceCenter/renku-ui/issues/1956

**Comment by ciyer** [comment]
The implementation will require a bit more than just `renku save`. It will need to do the following:

```
- git fetch
- git status --porcelain --branch: Should return that checkout is at or ahead of upstream, if not fail
- renku save
```

The second command should provide user-understandable feedback as to why the save couldn't run if it fails at that point.
