### ISSUE TITLE
should wait for server to be ready before redirecting

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#12]
If the notebook server takes a long time to spawn (e.g. because images have to be downloaded), JH will wait for 30 seconds and then redirect to a url like `.../hub/user/...` which fails with a 401 because it's not actually a valid URL (it still gets proxied to the notebooks service for some reason which queries gitlab for a non-existent project, hence the 401). 

The way to fix this is to wait until the server is ready before redirecting. It's unclear how to get this information.

moved from https://github.com/SwissDataScienceCenter/renku/issues/210 -- see https://github.com/SwissDataScienceCenter/renku/issues/210#issuecomment-394503121

**Comment by erbou** [comment]
Can we have a description of the symptoms of this bug? I am not sure if I am facing the same issue or if that should be another issue.
