### ISSUE TITLE
The pre-stop hook should try to push changes to remote

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#140]
Now we push uncommitted changes to an autosave branch, but perhaps even more important would be to push unpushed changes to origin. 

With the current implementation, committed but unpushed changes are lost (which uncommitted changes are pushed to the autosave branch). We need to also save the unpushed commits.

**Comment by mohammad-sdsc** [comment]
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/164

**Comment by rokroskar** [comment]
closed by #174
