### ISSUE TITLE
Better handle the case of a missing image

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#146]
When a user tries to launch a notebook server from an image which is missing (for whatever reason), the user is shown the `spawning` screen for a long time and eventually a `500`. The corresponding pod is in `ImagePullBackOff` state. It would be nice if the notebook server could report an `imagePullFailure` state to the UI which could display that state and offer a link for the user to go and re-trigger the image build job.

**Comment by rokroskar** [comment]
This shouldn't happen anymore since we check with the registry that the image is there before launching the session.

**Comment by ableuler** [comment]
This doesn't seem to be a problem anymore.
