### ISSUE TITLE
Investigate the feasibility of using PVs for user repositories.

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#149]
We have received requests for users to simply "drop in" to their environment as they left it previously. We could enable this by using PVs but we need to investigate what sort of defaults would make sense and how such volumes could be pruned. Some questions to ask:

- can we scale the volumes after they are created? 
- can we get information about when a volume was last used?
- can we easily prune inactive user volumes? 
- how can we report the volume usage?

**Comment by ableuler** [comment]
See also the discussion on https://github.com/SwissDataScienceCenter/renku-notebooks/issues/149. Preventing data loss for users due to pod eviction or node failures has priority over this issue for now.

**Comment by lorenzo-cavazzi** [comment]
@rokroskar was this closed in #573 ?

**Comment by rokroskar** [comment]
Yes, thanks for the reminder!
