### ISSUE TITLE
Save Session button fails 

### ISSUE THREAD

**Issue by noeleont** [SwissDataScienceCenter/renku-notebooks#1575]
## Description

After clicking on the Save Session button I get the following error:

<img width="550" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/2394624/97800008-9bf2-4e48-b06f-2acfc77b25ef">

## Reproduce

1. Start a project
2. Make changes
3. Click "Save Session"

I tried it with several projects, including a newly created, none worked.

**Comment by noeleont** [comment]
@olevski thanks for the update!

**Comment by Panaetius** [comment]
downgrading to python 3.10 might work
