### ISSUE TITLE
clicking "launch" for an existing notebook yields "bad request"

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#16]
If a server is already running, this is not handled properly.

**Comment by rokroskar** [comment]
yes, I've also seen that. I'm not sure atm how to solve that, I don't have any way of getting the state of the pods.

**Comment by leafty** [comment]
@rokroskar interacting with just the hub, yeah.

If it comes to it, you might also have to integrate the k8s python lib, with a read-only service account.

**Comment by rokroskar** [comment]
well it's particularly annoying because the hub clearly does keep up-to-date track of all the pods (I can see it in the logs). But I don't know how to get access to that information.
