### ISSUE TITLE
make it possible to spawn notebook servers from public repository without logging in

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-notebooks#171]
I would like to be able to spawn a notebook server, as an anonymous user (not a project team member) of a public project. This is for tutorials and classes, we do not need (should not be able) to to push changes done in the notebook.

**Comment by ableuler** [comment]
This issue will be resolved as part of the epic #275. We will allow users to launch a notebooks server without forcing them to log in at all.
