### ISSUE TITLE
Add hostname and path prefix back to notebook server url

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#173]
The recent refactoring of the code structure undid the changes implemented by https://github.com/SwissDataScienceCenter/renku-notebooks/commit/597b3ba19cf6fe6280a2a681d46e589d3b13a89a by accident.

**Comment by rokroskar** [comment]
oh no sorry about that...

**Comment by rokroskar** [comment]
@mohammad-sdsc wasn't this addressed in one of the merged PRs? Can we close it?

**Comment by mohammad-sdsc** [comment]
Yes, this is fixed and merged.
