### ISSUE TITLE
Use the k8s api for the `/servers` endpoint

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#177]
Instead of querying Jupyterhub for the information on the servers running for the user, query the k8s api directly. Here it would make sense to add `username` to pod labels so we can use that in the `label_selector` - we can then further identify the pods we need based on the project/commit-sha annotations. 

This endpoint should also return information about failed notebook launches so we can provide that information back to the user.

**Comment by rokroskar** [comment]
Since this is almost done and a much-needed improvement I have added it to the `0.4.0` milestone.

**Comment by mohammad-sdsc** [comment]
Currently, a `GET` request to the `/servers` endpoint returns a JSON response like this:
```json
{
    "servers": {
        "mohammad-2-new-2dproj-96a655a": {
            "annotations": {
                "renku.io/branch": "master",
                "renku.io/commit-sha": "96a655a",
                "renku.io/namespace": "mohammad.alisafaee",
                "renku.io/projectId": "109",
                "renku.io/projectName": "new-project"
            },
            "last_activity": "2019-06-17T06:31:24.553000Z",
            "name": "mohammad-2-new-2dproj-96a655a",
            "pending": null,
            "progress_url": "/jupyterhub/hub/api/users/mohammad.alisafaee/servers/mohammad-2-new-2dproj-96a655a/progress",
            "ready": true,
            "started": "2019-06-17T06:31:10.275517Z",
            "state": {
                "pod_name": "jupyter-mohammad-2-mohammad-2d2-2dnew-2d2dproj-2d96a655a"
            },
            "url": "/jupyterhub/user/mohammad.alisafaee/mohammad-2-new-2dproj-96a655a/"
        }
    }
}
```
When using Kubernetes API, some of these fields don't exists. The only one that matters to the UI is the `pending` fields which shows if a server is `spawning` or `stoping` or neither (i.e. null).

**Comment by mohammad-sdsc** [comment]
After discussion with @lorenzo-cavazzi, we decided that the new implementation returns a response like this:
```json
{
    "servers": {
        "mohammad-2-new-2dproj-96a655a": {
            "annotations": {
                "hub.jupyter.org/servername": "mohammad-2-new-2dproj-96a655a",
                "hub.jupyter.org/username": "mohammad.alisafaee",
                "renku.io/branch": "master",
                "renku.io/commit-sha": "96a655a",
                "renku.io/namespace": "mohammad.alisafaee",
                "renku.io/projectId": "109",
                "renku.io/projectName": "new-project"
            },
            "name": "mohammad-2-new-2dproj-96a655a",
            "url": "/jupyterhub/user/mohammad.alisafaee/mohammad-2-new-2dproj-96a655a/",
            "started": "2019-06-17T06:31:10.275517Z",
            "state": {
                "pod_name": "jupyter-mohammad-2-mohammad-2d2-2dnew-2d2dproj-2d96a655a"
            },
            "status": {
                "phase": "Running",
                "ready": true,
                "step": "Ready",
                "message": null,
                "reason": null
            }
        }
    }
}
```
The `phase`, `step`, `message`, and `reason` in `status` field come from [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase). If `status.ready` is not `true` then `step` along with `message` and `reason` show what is the current launch status of the server.

**Comment by rokroskar** [comment]
Why do you need the `hub.jupyter.org` annotations? The username should be a `renku.io` annotation and the other one is a duplicate of `name`.

**Comment by mohammad-sdsc** [comment]
These comes from Kubernetes as they are and I did not filter them. The old code was only including `renku.io` annotations which did not include the `username`. I can limit these to `renku.io` annotations if needed.

**Comment by rokroskar** [comment]
oh right, no that's fine. I forgot those were there already. IMHO it would be nicer to have the `username` be a renku-specific annotation.

**Comment by mohammad-sdsc** [comment]
Closed by https://github.com/SwissDataScienceCenter/renku-notebooks/pull/185.
