### ISSUE TITLE
Notebooks fail to launch (first time) [Buhler deployment]

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-notebooks#179]
### Steps to reproduce:
* Make sure no notebook was launched/used for a couple of hours and that there are enough resources
* Launch a notebook

### Result:
* No notebook is launched (no pod is created)
* No error messages in the logs, except from 
`[W 190618 10:49:58 cull_idle_servers:128] Not culling server delgadop/delgadop-adf-f4fdf22 with pending spawn`

This happens only the first time a notebook is launched after no notebooks are in use. The second time the notebook is launched fine.

### Logs:
[notebooks-20190618-1248.log](https://github.com/SwissDataScienceCenter/renku-notebooks/files/3301262/notebooks-20190618-1248.log)
[hub-20190618-1248.log](https://github.com/SwissDataScienceCenter/renku-notebooks/files/3301263/hub-20190618-1248.log)

Additional data from Clement:
[LogsNotebooksLaunchRenkuBuhler.docx](https://github.com/SwissDataScienceCenter/renku-notebooks/files/3301278/LogsNotebooksLaunchRenkuBuhler.docx)

**Comment by Clement-Lef** [comment]
Let me add some precision. We are only 2 users currently on this deployment. From what we noticed the common thing between the failure to launch a notebook is the time separating the launch from the last ones. Even if one user is currently working on a launched notebook, if someone else comes 1 hour later it will also fails to launch at first.

**Comment by rokroskar** [comment]
Sorry I'm just catching up with this now - the logs all look normal to me, without some more information from the kubernetes side it's hard to tell what's going on.

**Comment by pameladelgado** [comment]
After updating Renku to 0.4.2 we noticed this is no longer a problem.
Closing this issue.
