### ISSUE TITLE
feat: add resource information to pod annotations

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#223]
It should be easy to add a couple of extra annotations to the pods about the environment resources/options selected during the start phase. These could be added to the `/servers` endpoint and be used by the UI to give extra information (e.g. number of GPU available)

**Comment by rokroskar** [comment]
You could get the same information from the k8s api, no? I don't think going through pod annotations for determining resource availability is the way to go. Or am I misunderstanding the intent?

**Comment by lorenzo-cavazzi** [comment]
This is to easily recover the options chosen by the user at start time (e.g. 2 cpu/1gpu) and use them in the UI, not determining the overall resource availability (that is addressed by #222).

Anyway, I guess you are totally right, I don't need to add any extra annotation since all the information seems to be already available when invoking `kubectl describe`. Then it's just a matter of adding the missing information in the `/servers` api :slightly_smiling_face:

**Comment by rokroskar** [comment]
yes, when you retrieve the pod you can (should) get all of those options, afaik. I wouldn't add them to annotations unless there is something very renku-specific and not related to the characteristics of the pod.
