### ISSUE TITLE
Create a better server launch flow

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#24]
At the moment, we simply issue an API request to jupyterhub for a server spawn and wait until jupyterhub reports that this server is running. This is definitely not the way we want to handle server launches. 

We should improve the sequence to provide some extra feedback to the user about what is happening. Most importantly, the notebooks service flask app should not block waiting for the server to spawn. We should discuss how to move this forward -- some options: 

* if the server for `<namespace>/<project>/<sha>` is not running, the endpoint should return an page that shows the status of the pod/server being launched and a 202 return code 
* if the server for `<namespace>/<project>/<sha>` is running, the server/notebook is returned as normal
* the page with the status should redirect to the running server once it's up
* we should use k8s/docker clients for checking on the server spawn so we can report errors as they arise. If the pod launch errors, call `DELETE` on the JH API for the server so that it is immediately removed from the proxy etc. 
* ~~do we need a `<namespace>/<project>/<sha>/status` endpoint? Or just `<namespace>/<project>/<sha>?status`?~~ No, use CRUD and make `POST` launch the notebook, `GET` gives the status of the launch

Once this is done, it will most likely fix #23

**Comment by leafty** [comment]
@rokroskar Closed via #25?

**Comment by rokroskar** [comment]
yep.
