### ISSUE TITLE
Add files to dataset failed

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-notebooks#249]
I wanted to add 2.6gb of zip files to a dataset on https://dev.renku.ch/projects/renku-qa/sbb-data-qa/environments and went to get a coffee. When I came back there was a dialog informing me that the notebook was not running, with a button to restart the notebook. Clicking the button led to:
![image](https://user-images.githubusercontent.com/664486/75022115-cb8b8480-5495-11ea-8dd3-b4d940518f1a.png)

Going back to the notebook, there's now a new popup
![image](https://user-images.githubusercontent.com/664486/75022152-db0acd80-5495-11ea-8ead-2a1696e65819.png)
that just keeps reappearing when clicking ok.

On the main page, the environment is shown as pending (for 10 minutes at the time of writing) with no useful logs:
![image](https://user-images.githubusercontent.com/664486/75022825-0d68fa80-5497-11ea-90c5-96a7e538f011.png)

The logs on rancher for the pod show:
```
Warning 	Evicted 	Pod ephemeral local storage usage exceeds the total limit of containers 20Gi. 	40 minutes ago
Normal 	Killing 	Stopping container notebook 	40 minutes ago
Warning 	FailedPreStopHook 	Exec lifecycle hook ([/bin/sh -c /usr/local/bin/pre-stop.sh || true]) for Container "notebook" in Pod "jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dfaa5b8fe_renku(0414f623-5477-11ea-84b9-fa163edb299d)" failed - error: command '/bin/sh -c /usr/local/bin/pre-stop.sh || true' exited with 1: fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. error: src refspec renku/autosave/ralf.grubenmann/master/bbb7597/0fd2a5d does not match any. error: failed to push some refs to 'https://oauth2:699f208c022132799d5a27049105cb50c23f01f29f1ce1e335f417c3b066f907@dev.renku.ch/gitlab/renku-qa/sbb-data-qa.git' fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. error: branch 'renku/autosave/ralf.grubenmann/master/bbb7597/0fd2a5d' not found. , message: "fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
error: src refspec renku/autosave/ralf.grubenmann/master/bbb7597/0fd2a5d does not match any.
error: failed to push some refs to 'https://oauth2:699f208c022132799d5a27049105cb50c23f01f29f1ce1e335f417c3b066f907@dev.renku.ch/gitlab/renku-qa/sbb-data-qa.git'
fatal: Unable to create '/work/sbb-data-qa/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
error: branch 'renku/autosave/ralf.grubenmann/master/bbb7597/0fd2a5d' not found.
"
```

**Comment by rokroskar** [comment]
Seems to work as expected :) You exceeded the disk quota and was evicted. Then the pre-stop hook failed to execute... and I guess that caused the stuck state?

**Comment by Panaetius** [comment]
There's not really any indication for me as a new user who has no idea what's going on to know that there is a quota and to see how much of it I have used, an early indication would be nice to see.

And a normal user can't recover from this (had to manually kill the pod in rancher)

**Comment by rokroskar** [comment]
yeah I agree - it's more of a safety mechanism at this point to prevent users from crashing the nodes by filling up the disk. 

There are several related issues here - one is #148. The bigger issue is that I'm not sure how to communicate potential resource consumption issues and k8s API actions to the user. The same thing happens if the pod uses way too much memory - k8s will kill the process and the notebook kernel will die but the user usually won't even realize and wait forever for some cell to execute. Might be worth opening up a question on the jupyter discourse.

**Comment by Panaetius** [comment]
it's also weird that it logs you out of renku when this happens.

**Comment by rokroskar** [comment]
hmm that is probably not related... or is it? Maybe you can repeat it?

**Comment by Panaetius** [comment]
> hmm that is probably not related... or is it? Maybe you can repeat it?

After some further analysis, I think it might just be coincidence with the timeout of the session. Maybe we could increase the session lifetime, it seems to be a bit short at the moment, there's no reason to not keep a user logged in for a whole day.

**Comment by fgeorgatos** [comment]
fyi. I have also observed the "Directory not found" and 500 error, while importing https://zenodo.org/record/3632480 (declaring so, in case it helps to reproduce the bug)

**Comment by rokroskar** [comment]
> Maybe we could increase the session lifetime

which session?

**Comment by rokroskar** [comment]
@Panaetius I'm guessing you mean the interactive jupyter session - it's currently set to expire after 24 hours of inactivity in production, less on dev. I will close this as it doesn't seem to be an issue with the notebooks service but feel free to reopen if you disagree.
