### ISSUE TITLE
Push committed (but not-yet-pushed) work to "autopush" branch

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#268]
At carving through data, some not so experienced users have lost work by creating a commit from their work but forgetting to push it. It would be nice if our autosave checks could include this scenario.

**Comment by rokroskar** [comment]
I thought it did? Can you reproduce the problem? It should push the unpushed changes to the autosave branch.

**Comment by ableuler** [comment]
> I thought it did? Can you reproduce the problem? It should push the unpushed changes to the autosave branch.

@mohammad-sdsc told me the same. I did not reproduce this yet. I will give it a try.

**Comment by ableuler** [comment]
Tested this, works as advertised by @rokroskar and @mohammad-sdsc. Not sure what went wrong with the users as I was told after the fact. Closing this issue.
