### ISSUE TITLE
Consider pagination when using GitLab library

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#272]
Using `gitlab` library requires to consider [GitLab pagination](https://docs.gitlab.com/ce/api/#pagination)

Reference: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

**Comment by olevski** [comment]
I am looking through the current notebooks code and I cannot find an instance where we are getting a list of things from gitlab. As far as I can see in all cases we know ahead of time what we want to get (i.e. we know the branch, project, tag name) and we either get that or not. Happy to reopen if someone disagrees.
