### ISSUE TITLE
Allow session launch for unprivileged (but logged in) users

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#275]
The notebook launch sequence should be altered such that a logged in user without write access to a repo can still launch an interactive session. In this case, no oAuth token should be included in the repo URL.

**Comment by rokroskar** [comment]
I don't really think any changes are needed at all - we just need to skip the check in the service for gitlab authorization level.

**Comment by ableuler** [comment]
> I don't really think any changes are needed at all - we just need to skip the check in the service for gitlab authorization level.

That's basically what I wanted to say, but you thanks for the better description 😄
