### ISSUE TITLE
ensure that if content is json that it is included in response

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#369]
It appears that sometimes the notebooks service may be returning invalid JSON or no JSON at all even when JSON is set as the content type in the header. We should make sure that this is consistent everywhere - the manifestation is seen in errors arising from the UI handling 401 responses from the notebook service, presumably as a result of expired tokens. 

See [this sentry issue](https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/58/?referrer=github_integration) for examples.

**Comment by ableuler** [comment]
Do you know if this happens for one specific endpoint?

**Comment by rokroskar** [comment]
According to the sentry issue yes

**Comment by rokroskar** [comment]
It appears that this is not actually a problem in the notebooks service - may be fixed by some subset of https://github.com/SwissDataScienceCenter/renku/issues/934
