### ISSUE TITLE
Create a notebooks landing page

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#4]
The `<service-prefix>` endpoint right now just gives a JSON of the user object. It should give the authenticated user an overview of the running notebook servers and the means to stop them. 

One main issue to resolve is how to actually get the information about running servers per user. Right now this seems to be kept in the user object obtained through the `HubOAuthenticator` but this is cached via some (as of yet) to me obscure mechanism. Since the user info is cached, we don't get up-to-date info unless we reduce the caching timeout. There should be some way to query the hub directly, however. 

cc/ @ableuler @ciyer 

related to https://github.com/SwissDataScienceCenter/renku-ui/issues/151

**Comment by leafty** [comment]
Should that page live in the notebooks server? Or hitting it would redirect you to a UI page that does it? (While the actions are done on the notebooks service API)

**Comment by rokroskar** [comment]
@leafty yes the idea is that this would be a standalone feature of the notebooks app. That way it could be used even without the full renku UI if needed.

**Comment by leafty** [comment]
@rokroskar  I looked into the hub api code, and it looks like there is no endpoint for listing named servers. This can make implementing the landing page a bit tricky. And it also has the nasty side effect of defeating the purpose of cull-idle.

**Comment by rokroskar** [comment]
@leafty the running servers are reported as a part of the `user` object -- see https://github.com/SwissDataScienceCenter/renku-notebooks/pull/13/files#diff-0dd5359f832d9e504160cdcd45277fc7R158
