### ISSUE TITLE
Check if egress network policies can be used on user pods

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#413]
While introducing network policies would be a good thing in general at the [RenkuLab chart level](https://github.com/SwissDataScienceCenter/renku/issues/1435), network policies would be most needed to separate user pods from core RenkuLab pods (like the databases, etc). This could definitely be achieved by adding an ingress network policy to all the core RenkuLab pods, but it might also be achieved more easily by adding an appropriate egress network policy to the user pods.

**Comment by olevski** [comment]
See here: https://github.com/SwissDataScienceCenter/renku/pull/1541

However I think this should maybe be moved to the the renku-notebooks repo under: https://github.com/SwissDataScienceCenter/renku-notebooks/tree/master/helm-chart/renku-notebooks/templates. Not sure why I added my code to the renku repo.
