### ISSUE TITLE
Access control for projects with members in a group

### ISSUE THREAD

**Issue by ebiiii** [SwissDataScienceCenter/renku-notebooks#44]
https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/jupyterhub/spawners.py#L111
returns 404

in `access_level = gl_project.members.get(self.gl_user.id).access_level` : the members are only the manually added ones, not the ones belonging to a group (and the access was granted to the goup).

**Comment by rokroskar** [comment]
is there an API that gives you project permissions for the user in general?
