### ISSUE TITLE
Project with upper case is not started properly

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-notebooks#45]
The mounted volume (empty for) does not respect case at the moment. It results in a lab instance which cannot be used

Edit: This happens when converting existing projects to Renku (and not when creating them through the UI).

**Comment by rokroskar** [comment]
can you post relevant logs?

**Comment by leafty** [comment]
?!? It works on renkulab.io.

I think it's when converting an existing project which has uppercase in its gitlab path.

I'll have to check again later.

**Comment by rokroskar** [comment]
@leafty can you clarify if this is a problem or not?

**Comment by leafty** [comment]
See: https://renkulab.io/projects/107/ The project was created on gitlab.
When using `Launch JupyterLab`, the Files tab does not list the repo.

So this is an issue when "Renkufying" existing repos

**Comment by rokroskar** [comment]
it appears that the notebook container mounts the lowercase directory:

```
jovyan@jupyter-rok-2erosk-rok-2erosk--49-57ant--4ed3f22:~$ ls -l
total 16
drwxrwsrwx. 4 jovyan users 4096 Sep 18 12:31 iwanttotestthelimits
drwxr-sr-x. 2 root   root  4096 Sep 18 12:31 IWantToTestTheLimits
drwsrwsr-x. 2 jovyan users 4096 Jul 20 19:33 work

jovyan@jupyter-rok-2erosk-rok-2erosk--49-57ant--4ed3f22:~$ ls -la iwanttotestthelimits/
total 32
drwxrwsrwx. 4 jovyan users 4096 Sep 18 12:31 .
drwsrwsr-x. 1 jovyan users 4096 Sep 18 12:32 ..
-rw-r--r--. 1 jovyan users  305 Sep 18 12:31 Dockerfile
drwxr-sr-x. 9 jovyan users 4096 Sep 18 12:31 .git
-rw-r--r--. 1 jovyan users 3345 Sep 18 12:31 .gitignore
-rw-r--r--. 1 jovyan users  869 Sep 18 12:31 .gitlab-ci.yml
drwxr-sr-x. 2 jovyan users 4096 Sep 18 12:31 .renku
-rw-r--r--. 1 jovyan users    0 Sep 18 12:31 requirements.txt
```

Why? 🤷‍♂️

**Comment by rokroskar** [comment]
actually, it goes here: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/jupyterhub/spawners.py#L469

Which explains it perfectly :)

**Comment by leafty** [comment]
:laughing: Ahhh
Everything else respects the case, btw. From renkulab, you can sudo root and fix the folder with upper case.
