### ISSUE TITLE
Revisit necessary configuration and defaults

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#462]
In some code locations (both in the notebooks api and the spawner) we still make assumptions about defaults (like the gitlab URL) which could lead to failures or very unexpected results. We should replace those with sane assumptions wehre possible and fail gracefully where a configuration has to be set. See also https://github.com/SwissDataScienceCenter/renku-notebooks/pull/461#discussion_r525998670

**Comment by olevski** [comment]
I think we have improved things in this respect to some extent recently. The configuration of the notebooks is definitely leaner with the rollout of Amalthea.
