### ISSUE TITLE
Use dynamically created PVs for interactive sessions

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#464]
We create a dynamically provisioned PV (with its default retention policy `delete`) for each interactive session. The POST request to the `/servers` endpoint should accept a disk size parameter and the `GET` request to the `/server-options` should give a range or list of allowed sizes.

Open questions to be clarified and synced with the other components are:

- how does the user set the size of the volume?
- what are the allowed sizes, do we retain the volume for a period of time or is it immediately deleted when the session closes?
- improve/write documentation about managing data usage

### Update 4/2/2021:

following a design meeting, we have decided to implement the following: 

* allow the user to pick a volume size similar to the way memory and cpu are specified via a slider in the UI
* allow the user to set a default for the project in the project's configuration options
* allow the volume request in the user options to exceed the maximum value of the slider, with a hard-limit implemented and configured via the notebooks service

**Comment by rokroskar** [comment]
I might add here that the volumes should use a storage class with the `Delete` retain policy (so they are deleted after the pod terminates). It would be easiest to add such a storage class definition to the helm templates. We might in the future discuss some way of managing the lifetime of these volumes differently.
