### ISSUE TITLE
Explore options for fault-tolerant user sessions

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#465]
After https://github.com/SwissDataScienceCenter/renku-notebooks/issues/464 is resolved, we want to tie those PVs to more persistent k8s entities than just bare pods. The goal is that a users session will (after some time) become available again in the case of a node crash. Open questions that should be explored within the scope of this issue are:

- Can we create and expose anything else than just pods through Jupyterhub? (spawner, proxy)
- How will k8s reschedule a workload from a dead node? Are there some settings that could decrease the duration it takes for this to happen?
- What is the more appropriate concept to use here: `statefulSets` or `deployments`?

**Comment by olevski** [comment]
Addressed with Amalthea.
