### ISSUE TITLE
Fix/complete sentry setup in secret culling job

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#470]
The `SENTRY_DSN` environment variable is defined in the secret culling job, but parts of the setup are missing for sentry to work here:

- Use `.Values.sentry.dsn` instead of `.Values.sentryDsn`
- Add the `SENTRY_ENV` env variabl
- Import and initialize sentry in the python script (see [here](https://docs.sentry.io/platforms/python/#configure) for example).

**Comment by olevski** [comment]
The secret culling job is not required anymore.
