### ISSUE TITLE
enhancement: standardized error responses

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#545]
All errors from the API should adhere to the following schema:

```
class ErrorNested(Schema):
    message: fields.Str(required=True)
    detail: fields.Str(default: "")

class ErrorResponse(Schema):
    error = fields.Nested(
        ErrorNested(), required=True
    )
```

With this an error would look like this:
```
{
"error": {
       "message": "Invalid arguments.",
       "detail": "Argument A should be an integer.",  // this field can also be just blank ""
    }
}
```

A few questions:
- You mentioned you would also include a `code` field in the `ErrorNested` part. How do I come up with this code and how would you use it in the UI? Do we need another agreement between the UI and backend about what these codes mean?
- What happens if there are multiple errors? Should the `error` field be actually a list of the errors that were triggered? In that case should the error field always be a list?
- Is it ok to not have a detailed message in all cases i.e. `default=""`?

**Comment by lorenzo-cavazzi** [comment]
I really like this solution!
To answer the single questions:

* Having the `code` would be helpful to categorize the error type. No formal agreement would be required; listing all the codes with a short description in a single file would be enough. We can start without this and add the extra field later if we really need it.
* That's a good question. I believe providing a single error should be enough in all cases. I guess the code generally stops at the first exception, and everything else would be part of the StackTrace that I wouldn't add to the response. We may actually have multiple errors in some cases (e.g. the user providing more than 1 invalid fields), but I guess the `message` would be similar and the details could be collapsed in a single string: 
```
{
    "error": {
        "message": "Invalid arguments.",
        "detail": "Argument A should be an integer. Argument B should be a string. Argument C is not supported"
    }
}
```
If you believe it's safer to have multiple errors, I would then go for having `errors` as an array in all cases.
```
{
    "errors": [
        {
            "message": "Invalid arguments.",
            "detail": "Argument A should be an integer. Argument B should be a string. Argument C is not supported"
        }
    ]
}
```
* Yes, either an empty string or `null` is ok.

**Comment by olevski** [comment]
@lorenzo-cavazzi , thanks for the feedback.

I agree with your suggestions:
- I will add a code to the response and document the codes somewhere in the docs for the api
- There will always only be one error and not an array of errors. This is simpler for me as well
- The detail field will not always have a value - if there is no value the default will be null.

With this in mind the schema would be like this:
```python
class ErrorNested(Schema):
    message = fields.Str(required=True)
    detail = fields.Str(default: None)
    code = fields.Integer(required=True)

class ErrorResponse(Schema):
    error = fields.Nested(
        ErrorNested(), required=True
    )
```
