### ISSUE TITLE
optimize user pod placement

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#570]
Because our user session pods use ephemeral volumes, we have decided since the beginning to not use the JupyterHub-provided scheduler, which "packs" pods into nodes to make it easier to upscale/downscale the cluster. By distributing the pods more evenly across the nodes we minimize the risk of running out of disk space. 

This is a terrible design for many reasons and will be changed with #464. Once this is done, we should feel more at ease packing the nodes as full as possible, which will allow us to decommission nodes that are idle, saving resources and allowing for auto-scaling the cluster wherever possible. 

The only change required here should be to turn back on the custom JupyterHub scheduler after #464 is complete (see [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#using-available-nodes-efficiently-the-user-scheduler)).

**Comment by olevski** [comment]
Addressed by https://github.com/SwissDataScienceCenter/terraform-renku/pull/133
