### ISSUE TITLE
Remove PVS for older commits

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#576]
As a follow-up to #573 , we may want to get rid of stale PVS.
We can imagine that a user won't need the PVS anymore when he starts a pod from a more recent commit. That means we could add to the `POST /servers` the logic to check if there are other PVS for the same repo that were created from an ancestor commit, or from a branch merged to the target branch.

**Comment by olevski** [comment]
@lorenzo-cavazzi so this logic should be implemented for autosave branches as well just to be consistent, right?

Also, just to make sure we are on the same page can you confirm that these are the two cases where we should remove old pvcs that do not have a running pod associated with them?

Case 1: If a user launches a session at A and there is an old pvc without a pod at B, then delete pvc at B
```
A (HEAD)
|
_______
|     |
|     |
      B
```

Case 2: If a user launches a session at A and there is an old pvc without a pod at B, then delete pvc at B
```
A (HEAD)
|
|
B
|
|
```

**Comment by lorenzo-cavazzi** [comment]
Those 2 cases are correct.
I think it makes sense to adopt the same policy with autosaved branches. The one difference is that the user can actually see them in GitLab, even though we already remove them automatically and users can't rely on them even now.
