### ISSUE TITLE
Allow user to discard previous content when starting a new environment

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#586]
With PVS we have now 2 ways to restore previous content when starting a new interactive environment. With #584 the user should be able to get a clear indication of the existence of any previous work.

We should provide a way to discard that content and start a clean environment (related: SwissDataScienceCenter/renku-ui#1143). An easy solution would be adding an additional parameter in the body when invoking the `POST /servers` API (`discard_autosave` ?).

That should either:
- Remove the GitLab autosaved branch.
- Remove the old PVS

**Comment by ableuler** [comment]
I think we should also consider https://github.com/SwissDataScienceCenter/renku-notebooks/issues/465 in this discussion. Once we elevate user sessions from pods to statefulSets or deployments, sessions won't disappear anymore unless culled or explicitly stopped. Considering also https://github.com/SwissDataScienceCenter/renku-notebooks/issues/577, my preferred UX would be:
- Session PVs are tied to one session and have the exact same lifecycle as the session. There's no case where we launch a new session but we already have a volume for it hanging around.
- We try to prevent the creation of autosave branches by warning the user about unsaved work already when stopping the session. 
- Autosave branches are created only when culling a session, or when k8s for some other reason forcefully removes the session statefulset/deployment. Whenever we have such an autosave branch, we provide an easy way to ignore it as suggested above by @lorenzo-cavazzi .
