### ISSUE TITLE
chore: make acceptance tests with user PVs run in CI pipeline

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#588]
Based on #573 the CI pipeline would need admin privileges to deploy renku notebooks with the features that makes user sessions use PVs. Resolving this issue would make this possible ideally without granting k8s admin privileges to renku bot. It could be that through rancher somehow this is possible (maybe).

**Comment by ableuler** [comment]
Hmm, not sure I understand. Aren't the role and role binding that are part of the notebooks-service helm templates all that's necessary to interact with PVCs?

**Comment by olevski** [comment]
Done
