### ISSUE TITLE
add the jupyterlab-git extension to default image

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#61]
Since https://github.com/jupyterlab/jupyterlab-git/pull/210 has been merged, should we add the extension by default?

**Comment by leafty** [comment]
@rokroskar it's merged, but not on PyPI

**Comment by rokroskar** [comment]
Aha of course that would explain it

**Comment by leafty** [comment]
I'm trying it with
```
RUN jupyter labextension install @jupyterlab/git && \
    pip install -e git+https://github.com/jupyterlab/jupyterlab-git.git#egg=jupyterlab-git && \
    jupyter serverextension enable --py jupyterlab_git
```
but I think jupyterlab needs some upgrade too.

It sees the git repo, but I can't commit for some reason.

**Comment by rokroskar** [comment]
well that's actually the same thing I saw...

**Comment by rokroskar** [comment]
done in #64
