### ISSUE TITLE
enhancement: add sizeLimit to emptyDir used for user sessions

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#648]
This can be done like this in `spawners.py` at line 215:
```
if not options.get("pvc_name"):
    volume = {
        "name": git_volume_name,
        "emptyDir": {"sizeLimit": server_options.get("disk_request", "1G")},
    }
```

Pods are then evicted very quickly after the emptyDir goes over the limit:
```
  Normal   Created              6m20s  kubelet            Created container git-https-proxy
  Normal   Started              6m19s  kubelet            Started container git-https-proxy
  Warning  Evicted              62s    kubelet            Usage of EmptyDir volume "jupyter-tasko-2eolevskitestprivate-2dce351525-git-repo" exceeds the limit "1G".
  Normal   Killing              62s    kubelet            Stopping container notebook
  Normal   Killing              62s    kubelet            Stopping container git-https-proxy
```

However, the evicted status is not properly communicated to the UI s.t. the sessions can be deleted. Currently the UI shows the user sessions as if it was just stuck in "loading" and it does not provide the option to delete the session from the UI.

**Comment by lorenzo-cavazzi** [comment]
If there is a way to get that information from the status we get from the `GET /servers`, we can easily adapt the UI to support that interaction. That works if the information is there some time (at least 1 min). Otherwise, it's a bit more complicated

**Comment by olevski** [comment]
I will reopen a new issue to inform user when a session is evicted because of consuming too much memory, disk or other resources that have limits. Not sure how easy it is to do this since the eviction from k8s happen very quickly (i.e. within less than a minute for disk space).
