### ISSUE TITLE
spawners: cache LFS objects on separate volume

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-notebooks#67]
Set Git config `lfs.storage` to a separate volume that can be shared among notebook servers spawned for the same project.

**Comment by leafty** [comment]
While this can be a good idea, how will we be providing the shared volumes?

**Comment by rokroskar** [comment]
Don't think this is going to happen. Instead we are investigating ways of streaming data directly from LFS.
