### ISSUE TITLE
Image availability check fails when project visibility is "internal"

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#739]
With visibility "internal", logged-in but otherwise unprivileged users can see the images in the registry, but do not have access to the CI/CD pipelines API. However, for those users we're currently trying to establish the image existence by querying the pipelines API which then fails.

**Comment by olevski** [comment]
@ableuler I am having trouble replicating this. I tested by launching a session from the swagger page on renkulab and things worked. In the notebooks we do not look at the pipelines at all to see if an image is available - we just go straight to the docker api.

My guess would then be that the UI checks the pipelines. But I had issues replicating this problem with either the new or old UI. So I guess it has been fixed?

**Comment by ableuler** [comment]
Hmm, this is strange. First of all you are of course right that the call to the pipeline / jobs api comes from the UI, but second it seems to me that default project settings for internal projects do indeed allow every body with access to the instance to also see the pipelines / jobs. The project which triggered this issue has now different visibility settings, so I won't be able to check back on it. Let's close this.
