### ISSUE TITLE
Make Streamlit/Rshiny or similar apps work with Amalthea

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#741]
As far as I can see currently these types of apps will not work with Amalthea. We should figure out how to make this possible.

**Comment by olevski** [comment]
This is caused by streamlit trying to access the jupyterlab server before it is ready. Should be fixed by properly implementing readiness/liveness/startup probes in k8s.

**Comment by ableuler** [comment]
Hmm, I didn't have this on my radar. Guess we need the HTTP based probe sooner rather than later?
