### ISSUE TITLE
Move git clone back to an init container

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#743]
The idea was to have git credentials only stored in one location (the git http proxy) and use that proxy for the clone. However, this makes it impossible to do the clone in an init container, and we've moved it to the entrypoint of the git sidecar instead. However, this introduces some race conditions between the different entrypoints which need to be fixed using some rather hacky approaches, so it's probably cleaner to move the cloning back into a dedicated init container which has access to the users credentials and doesn't use the git http proxy.

**Comment by olevski** [comment]
Addressed with in #668
