### ISSUE TITLE
Session summary does not show GPU, if they are used

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-notebooks#775]
## Description

The "Resources" summary on the Session page does not show GPU use. This is relevant for deployments powered with GPUs.
As seen on SV-Renku:
![image](https://user-images.githubusercontent.com/22785147/136530367-bef3d51a-809b-4d77-97b2-a54b29f35296.png)
GPU access is confirmed with `nvidia-smi`:
![image](https://user-images.githubusercontent.com/22785147/136530457-6c9617eb-3e16-48f0-9a77-17b4d8ed16c8.png)

## Reproduce

1. Go to a GPU powered Renku instance, like limited or SV
2. Start a session with GPUs
3. Go to the sessions page for the project
4. See that CPU, Memory and Storage are shown, but not GPU.

## Context

- renkulab url: sv-renku.epfl.ch
- operating system and version: Mac OS
- browser and version: Safari

**Comment by olevski** [comment]
Thanks @lorenzo-cavazzi for tracking this down. And @gavin-k-lee for reporting. This was addressed recently in: #786 

And it works currently on limited:
![image](https://user-images.githubusercontent.com/16360283/142007072-3f0a177f-cd78-44d9-bf45-245c5870c99b.png)
