### ISSUE TITLE
Modify `cache-control` header for `server_options` endpoint

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#78]
Currently, the notebook service sets a `max-age` value of 12 hours on the `cache-control` header for the `server_options` endpoint. I assume that this was not set on purpose, but that it's just a side-effect from serving the json as a static file. I suggest to dramatically reduce this value or to remove the header all together.

**Comment by rokroskar** [comment]
Does it help if the file is read and the json returned instead of using `send_file`?

**Comment by ableuler** [comment]
Yes, reading it into a dictionary and then serializing into a JSON response seems the clean way to go. However it's not urgent anymore. My suggestion is just a quick fix. Anyway, now that I know what's going it's not that urgent anymore, I have means to prevent the usage of the browser cache from the client side too.
