### ISSUE TITLE
Create automated action that updates fall back image when renkulab-docker has a new release

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#792]
If I launch a session now with the default image (because the image build failed, for example) I get `renku/singleuser:latest` which is super old. We should update this to start with the image that is the base image for the current template version.

**Comment by olevski** [comment]
Addressed by #803

@rokroskar if the image that comes with the request to launch a session is not available the notebook service cannot do that much. We could clone the repo and check the Dockerfile and then try to use the base image but I don't think this will be very efficient to do with every request to launch a session.

So I think we are stuck with having a hardcoded value.

**Comment by rokroskar** [comment]
yes, my point was just that the hard-coded value should be updated, ideally by CI triggered in the `renkulab-docker` repo.

**Comment by olevski** [comment]
@rokroskar then I will rename this issue to say something like: "Create automated action that updates fall back image when renkulab docker has a new release".

**Comment by rokroskar** [comment]
yeah and tbh it shouldn't even be in this repo then... I just really wanted a one-liner that updated the image now and handle the full solution later. But we can just move the issue to renkulab-docker if you want
