### ISSUE TITLE
allow egress to any port as long as it is outside of the cluster

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#798]
Users want to be able to connect to external services that may run on any port. An example of this is connecting to an external postgres database. We should allow such connections to take place _as long as they are outside of the cluster_ to prevent any unwanted access to local databases and other resources.

**Comment by olevski** [comment]
Yeah we were a bit too extreme here with preventing egress:
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/430

**Comment by rokroskar** [comment]
I think it's definitely a good idea to be more conservative than not!

**Comment by TaoSunVoyage** [comment]
FYI @erbou, this might help for spark as well. Have direct communication without Livy and Spark-Magic?
