### ISSUE TITLE
how to remove pending servers

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#80]
It appears that JH doesn't offer an API for removing spawning servers. We should somehow be able to remove them, however, if e.g. someone tries to spawn a server and a requested number of GPUs are not available.

**Comment by leafty** [comment]
Would it make sense to resolve this by contributing to kubespawner?

**Comment by olevski** [comment]
This should be moved to amalthea where pending servers are automatically culled after X hours.

**Comment by olevski** [comment]
This has been moved to amalthea here: https://github.com/SwissDataScienceCenter/amalthea/issues/125
