### ISSUE TITLE
Wrong branch checked out

### ISSUE THREAD

**Issue by TaoSunVoyage** [SwissDataScienceCenter/renku-notebooks#801]
If user now starts a session from a branch other than master,  user will still have master branch checked out in the session.

Test project: https://renkulab.io/projects/tao.sun/test-branch/

<img width="1023" alt="Screenshot 2021-11-11 at 16 53 42" src="https://user-images.githubusercontent.com/30494890/141328275-4089a9c4-b794-4827-895e-1e4e0019b188.png">

**Comment by olevski** [comment]
Thanks for spotting this Tao. I found the issue. I will submit a PR to correct it.

**Comment by TaoSunVoyage** [comment]
Great, thanks @olevski !
