### ISSUE TITLE
Set CPU limits on user pods

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#817]
Currently, we do not place any limit on the CPU consumption of user pods. The original idea behind this was that user pods should be able to temporarily overshoot in CPU consumption as long as a node still has free resources. However, this is a risky business if resource needs of system pods or even of non-pod k8s components such as the kubelet are not properly protected. In that case, it's actually fairly easy to starve essential components from CPU just by being super greedy inside a session. I therefore think that this is an aggressive setting and that the default should instead be to place a limit which is equal to the request for both memory and CPU on the user pods. We can still leave it as a conscious decision to admins to deploy the notebooks service in the setting that we currently have as default.

**Comment by ableuler** [comment]
On our renkulab instance for example, even though we're limiting the allocatable CPU to 7.5 vCPU per node, user pods can consume CPU in excess of that:
![image](https://user-images.githubusercontent.com/13014091/142989630-299beddf-ca50-4d5d-a884-c0ff2acac721.png)

**Comment by ableuler** [comment]
@rokroskar @olevski what do you think about this?

**Comment by rokroskar** [comment]
yeah I think imposing limits makes sense. I think it's what users expect, anyway.

**Comment by rokroskar** [comment]
we'll get more users requesting sessions with more CPU but it will give us more realistic scheduling probably

**Comment by olevski** [comment]
Yeah I think it makes sense to have some limits.
