### ISSUE TITLE
streamlit app infinitely reloads for larger data sets

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-notebooks#846]
Dear renku team,

in a project, renku is used to deploy streamlit apps (https://renkulab.io/projects/msei/msei-main). The app of concern is called `streamlit_KMD` and is run from the file `src/KMDvalues_streamlit.py`. In the app, a data set can be selected, which is then loaded and some visualizations are created and displayed for it.

There are 4 data sets in the project, 2 smaller and 2 larger ones.
When running the app on my computer (ubuntu 20.04) from a conda env (no docker container...), it runs smoothly for all 4 data sets.
When running the app on renkulab, it runs smoothly for the 2 smaller data sets but ends up in an infinite loop for the 2 larger data sets. After around 10-15 seconds, the app restarts and starts loading the data again. And so on....

@ableuler hypothesized that this has something to do with all the information which needs to be exchanged between the different parts (he for sure can explain that better than I just did). 
Increasing the "probe time" to 60 instead of 10 seconds didn't change anything regarding that problem.

Please let me know if you need additional information and/or access to that non-public repo.

Thanks in advance!
Lili

**Comment by ableuler** [comment]
Yes, I was wondering if the the larger dataset increased the loading time of the app and thus the application didn't become available in time to answer to the readiness/liveness probes. Was just a quick thought, as mentioned by @LiliGasser a quick attempt to manually increase the probe timeout didn't help, so I think trying to run this session inside docker locally would be the next thing to try.

**Comment by gavin-k-lee** [comment]
Hi @LiliGasser - whilst I'm not an expert on Streamlit I'd be happy to have a look and see what's going on. Can you add me to the repo? Thanks

**Comment by LiliGasser** [comment]
@gavin-k-lee found the issue. It was something unrelated to renku. Thanks @gavin-k-lee !

**Comment by olevski** [comment]
I will close this issue since it has been resolved and is unrelated to renku. Thanks a lot @gavin-k-lee for debugging.
