### ISSUE TITLE
Add /version endpoint

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-notebooks#879]
Renku notebooks should expose a public `GET /version` endpoint.

The response format should be the following one:
```
{
    "name": string,
    "versions": [
        {
            "version": string,
            "data": object
        }
    ]
}
```

* "name" will be `renku-notebooks`
* "version" should be a SemVer valid value, possibly the tag or some combination of last tag + commit short-sha if it's a dev version
* "data" is optional, and it can be any arbitrary valid JSON object.

**Comment by olevski** [comment]
I like the addition of the `data` field. That is where I can put stuff like whether anonymous sessions or s3 mounting is enabled.

**Comment by olevski** [comment]
Thanks for the clear writeup @lorenzo-cavazzi!
