### ISSUE TITLE
Convert git-clone script to python

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#882]
At almost 200 lines and some not so simple logic all implemented in bash I think it may be a good idea to use python here.

This way we can write some unit tests for this. And it should make things a bit more easier to understand.

**Comment by Panaetius** [comment]
https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/git-clone/clone.sh

**Comment by rokroskar** [comment]
done in https://github.com/SwissDataScienceCenter/renku-notebooks/pull/956
