### ISSUE TITLE
notebooks: launch multiple servers for different branches

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-notebooks#90]
- [ ] ` ?branch=<name>` should create a server with different name that includes branch name

https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/src/notebooks_service.py#L102-L113

**Comment by mohammad-sdsc** [comment]
Users of notebook API should be able to start notebook servers for different branches of the same project. At the moment, users can only start notebooks from the `master` branch.
