### ISSUE TITLE
Return absolute instead of relative URLs

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#95]
URLs returned by the notebook service api should be absolute, i.e. include the host name. 
```
...
url: "/jupyterhub/user/cramakri/cramakri-weather-2d-9789210/"
```
should become 
```
'''
url: "https://renkulab.io/jupyterhub/user/cramakri/cramakri-weather-2d-9789210/"
```
such that the UI can open that URL directly when opening a notebook server tab for the user.

**Comment by rokroskar** [comment]
Leaving this open, but will not work on it until we start to rework the API

**Comment by ableuler** [comment]
I would like to increase the priority for this one. Once this issue is resolved, the UI does not need to be aware anymore of the Jupyterhub URL and depends on the gateway only. This will also make the helm charts less entangled.
