### ISSUE TITLE
Session backup

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-notebooks#96]
Sometimes notebook instances stop (e.g. node enters an out of memory condition) and current work is permanently lost.

Is there a way to provide some form of backup for these cases?

**Comment by rokroskar** [comment]
in principle, the data is on a volume so it should be recoverable... but I think `emptyDir` is tied to the pod lifetime, correct?

**Comment by leafty** [comment]
yes, that's why the current state is lost. but the fact that the notebooks are in volume (even `emptyDir`) means we could think of having a guaranteed sidekick pod to regularly save notebook files

**Comment by rokroskar** [comment]
or we could persist the volume until either a) the next time the user launches a server or b) some reasonable time has elapsed. If a user re-launches the same commit of the project after a crash, they get back to the same volume.

**Comment by leafty** [comment]
But then: how?

**Comment by rokroskar** [comment]
We have a mapping of `<namespace>/<project>/<commit-sha>` to a unique volume name and before launch we check if this volume already exists. If it does, we just re-attach. If not, we make a new one.

**Comment by rokroskar** [comment]
I just don't know what options we have for volume persistence. I guess not many.

**Comment by leafty** [comment]
Yeah, I'm not even sure the number is at least 1.

**Comment by rokroskar** [comment]
The other option is to periodically push to some remote branch -- I don't like this, personally. Though I suppose there could be a "scratch" branch. This still requires that the user commits, however, which may not happen at regular enough intervals.
